/**
 * @file EEPROM.c
 * @brief Implementation of EEPROM-Functions
 */

#include "main.h"
#include "InstructionList.h"
#include "STM_FUNCTIONS.h"
#include "EEPROM.h"

/**
 * @brief I2C object generated by HAL
 */
extern I2C_HandleTypeDef hi2c1;

/**
  * @brief Reads one byte from the EEPROM
  * @param address Address of the byte
  * @return The byte at the given address
  */
uint8_t EEPROM_ReadByte(uint16_t address)
{
	uint8_t data;

	HAL_I2C_Mem_Read(&hi2c1,
	                 0x50 << 1,
	                 address,
	                 I2C_MEMADD_SIZE_16BIT,
	                 &data,
	                 1,
	                 HAL_MAX_DELAY);

	return data;
}

/**
  * @brief Writes one byte to the EEPROM
  * @param address Address to write the byte at
  * @param data The byte to be written
  */
void EEPROM_WriteByte(uint16_t address, uint8_t data)
{

	HAL_I2C_Mem_Write(&hi2c1,
	                  0x50 << 1,
	                  address,
	                  I2C_MEMADD_SIZE_16BIT,
	                  &data,
	                  1,
	                  HAL_MAX_DELAY);

	while (HAL_I2C_IsDeviceReady(&hi2c1, 0x50 << 1, 1, HAL_MAX_DELAY) != HAL_OK);
}


//Documented in .h
Instruction EEPROM_GetInstruction(int position)
{
	position = position*4;
	Instruction in;
	in.functionNumber = EEPROM_ReadByte(position);
	in.data = EEPROM_ReadByte(position+1);
	in.data2 = EEPROM_ReadByte(position+2);
	in.data3 = EEPROM_ReadByte(position+3);
	return in;
}

//Documented in .h
uint8_t EEPROM_GetFunctionNumber(int position)
{
	position = position*4;
	return(EEPROM_ReadByte(position));
}

//Documented in .h
void EEPROM_PutInstruction(Instruction in, int position)
{
	position = position*4;
	EEPROM_WriteByte(position, in.functionNumber);
	EEPROM_WriteByte(position+1, in.data);
	EEPROM_WriteByte(position+2, in.data2);
	EEPROM_WriteByte(position+3, in.data3);
}


//Documented in .h
void EEPROM_EraseAll()
{
	for(int i = 0; i <= 0xFFF; i++)
	{
		EEPROM_WriteByte(i,0);
	}
}

